version: '3'

networks:
  backend:
    driver: ${NETWORKS_DRIVER}

volumes:
  mysql:
    driver: ${VOLUMES_DRIVER}
  redis:
    driver: ${VOLUMES_DRIVER}

services:
  ### NGINX Server #########################################
  nginx:
    restart: always
    build:
      context: ./nginx
    volumes:
      - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}
      - ${DATA_PATH_HOST}/nginx/logs:/var/log/nginx
      - ${DATA_PATH_HOST}/nginx/sites:/etc/nginx/sites-available
      - ${DATA_PATH_HOST}/nginx/ssl:/etc/nginx/ssl
    ports:
      - "${NGINX_HOST_HTTP_PORT}:80"
      - "${NGINX_HOST_HTTPS_PORT}:443"
    networks:
      - backend
    logging:
      driver: "json-file"
      options:
        max-size: "5g"

  ### Gitlab ################################################
  gitlab:
    restart: always
    #image: 'gitlab/gitlab-ce:11.1.4-ce.0'
    #image: 'gitlab/gitlab-ce:11.11.8-ce.0'
    #image: 'gitlab/gitlab-ce:12.0.12-ce.0'
    #image: 'gitlab/gitlab-ce:12.10.14-ce.0'
    #image: 'gitlab/gitlab-ce:13.0.14-ce.0'
    image: 'gitlab/gitlab-ce:13.12.12-ce.0'
    # hostname: '${GITLAB_DOMAIN_NAME}'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url '${GITLAB_DOMAIN_NAME}' #gitlab域名
        gitlab_rails['time_zone'] = 'Asia/Shanghai' # 时区
        gitlab_rails['gravatar_plain_url'] = 'http://sdn.geekzu.org/avatar/%{hash}?s=%{size}&d=identicon' # 允许自定义头像 http
        gitlab_rails['gravatar_ssl_url'] = 'https://sdn.geekzu.org/avatar/%{hash}?s=%{size}&d=identicon' # 允许自定义头像 https
        # gitlab_rails['registry_enabled'] = true
        # gitlab_rails['registry_host'] = ''
        # gitlab_rails['registry_port'] = 5000
        # 需要配置到 gitlab.rb 中的配置可以在这里配置，每个配置一行，注意缩进。
        # 比如下面的电子邮件的配置：
        # gitlab_rails['smtp_enable'] = true
        # gitlab_rails['smtp_address'] = "smtp.exmail.qq.com"
        # gitlab_rails['smtp_port'] = 465
        # gitlab_rails['smtp_user_name'] = "xxxx@xx.com"
        # gitlab_rails['smtp_password'] = "password"
        # gitlab_rails['smtp_authentication'] = "login"
        # gitlab_rails['smtp_enable_starttls_auto'] = true
        # gitlab_rails['smtp_tls'] = true
        # gitlab_rails['gitlab_email_from'] = 'xxxx@xx.com'
    volumes:
      - ${DATA_PATH_HOST}/gitlab/config:/etc/gitlab
      - ${DATA_PATH_HOST}/gitlab/data:/var/opt/gitlab
      - ${DATA_PATH_HOST}/gitlab/logs:/var/log/gitlab
    ports:
      - "${GITLAB_HOST_HTTP_PORT}:80"
      - "${GITLAB_HOST_HTTPS_PORT}:443"
      - "${GITLAB_HOST_SSH_PORT}:22"
    networks:
      - backend


