version: '3'

networks:
  backend:
    driver: ${NETWORKS_DRIVER}

volumes:
  mysql:
    driver: ${VOLUMES_DRIVER}
  redis:
    driver: ${VOLUMES_DRIVER}

services:
  ### NGINX Server #########################################
  nginx:
    restart: always
    build:
      context: ./nginx
    volumes:
      - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}
      - ${DATA_PATH_HOST}/nginx/logs:/var/log/nginx
      - ${DATA_PATH_HOST}/nginx/sites:/etc/nginx/sites-available
      - ${DATA_PATH_HOST}/nginx/ssl:/etc/nginx/ssl
    ports:
      - "${NGINX_HOST_HTTP_PORT}:80"
      - "${NGINX_HOST_HTTPS_PORT}:443"
    networks:
      - backend
    logging:
      driver: "json-file"
      options:
        max-size: "5g"

  ### Gitlab ################################################
  gitlab:
    image: 'twang2218/gitlab-ce-zh:11.1.4'
    # hostname: '${GITLAB_DOMAIN_NAME}'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url '${GITLAB_DOMAIN_NAME}'
        gitlab_rails['time_zone'] = 'Asia/Shanghai'
        # 需要配置到 gitlab.rb 中的配置可以在这里配置，每个配置一行，注意缩进。
        # 比如下面的电子邮件的配置：
        # gitlab_rails['smtp_enable'] = true
        # gitlab_rails['smtp_address'] = "smtp.exmail.qq.com"
        # gitlab_rails['smtp_port'] = 465
        # gitlab_rails['smtp_user_name'] = "xxxx@xx.com"
        # gitlab_rails['smtp_password'] = "password"
        # gitlab_rails['smtp_authentication'] = "login"
        # gitlab_rails['smtp_enable_starttls_auto'] = true
        # gitlab_rails['smtp_tls'] = true
        # gitlab_rails['gitlab_email_from'] = 'xxxx@xx.com'
    volumes:
      - ${DATA_PATH_HOST}/gitlab/config:/etc/gitlab
      - ${DATA_PATH_HOST}/gitlab/data:/var/opt/gitlab
      - ${DATA_PATH_HOST}/gitlab/logs:/var/log/gitlab
    ports:
      - "${GITLAB_HOST_HTTP_PORT}:80"
      - "${GITLAB_HOST_HTTPS_PORT}:443"
      - "${GITLAB_HOST_SSH_PORT}:22"
    networks:
      - backend

  ### DOCKER-REGISTRY ################################################
  docker-registry:
    build:
      context: ./docker-registry
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DATA_PATH_HOST}/docker-registry:/var/lib/registry
    ports:
      - "${DOCKER_REGISTRY_PORT}:5000"
    networks:
      - backend

### DOCKER-WEB-UI ################################################
  docker-web-ui:
    build:
      context: ./docker-web-ui
    environment:
      - TZ=PRC
      - ENV_DOCKER_REGISTRY_HOST=docker-registry
      - ENV_DOCKER_REGISTRY_PORT=${DOCKER_REGISTRY_PORT}
      - ENV_DOCKER_REGISTRY_USE_SSL=${DOCKER_REGISTRY_USE_SSL}
      - ENV_MODE_BROWSE_ONLY=${DOCKER_REGISTRY_BROWSE_ONLY}
    volumes:
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "${DOCKER_WEBUI_PORT}:80"
    networks:
      - backend

